from pydantic import BaseModel, EmailStr,Field
from typing import Optional, List

# --- User Schemas ---
class UserBase(BaseModel):
    """Base schema for user data."""
    email: EmailStr
    username: str

class UserCreate(UserBase):
    """Schema for user creation (includes password)."""
    password: str

class User(UserBase):
    """Schema for returning user data (excludes password hash)."""
    id: int

    class Config:
        # Allows ORM models (SQLAlchemy) to be converted to this Pydantic model
        from_attributes = True 

class UserInDB(User):
    """Schema for user data stored in the database (includes hashed password)."""
    hashed_password: str

# --- Token Schemas ---
class Token(BaseModel):
    """Schema for the access token response."""
    access_token: str
    token_type: str

class TokenData(BaseModel):
    """Schema for the JWT payload data."""
    email: Optional[str] = None

# --- AI Feature Schemas ---
class ChatRequest(BaseModel):
    """Schema for the chatbot input."""
    message: str

class FeedbackBase(BaseModel):
    """Schema for collecting feedback."""
    name_display: Optional[str] = None
    message: str

class FeedbackCreate(FeedbackBase):
    """Schema for creating feedback in DB."""
    pass

class Feedback(FeedbackBase):
    """Schema for returning feedback."""
    id: int
    user_id: int
    timestamp: str

    class Config:
        from_attributes = True

# Timetable Schemas (assuming the schedule is complex JSON)
class TimetableBase(BaseModel):
    """Schema for timetable data structure."""
    input_constraints_json: str
    schedule_json: str

class TimetableCreate(TimetableBase):
    """Schema for creating a timetable entry."""
    pass

class Timetable(TimetableBase):
    """Schema for returning a timetable entry."""
    id: int
    user_id: int
    timestamp: str

    class Config:
        from_attributes = True

# --- NEW VIDEO LEARNING HUB SCHEMAS ---
class TopicVideoRequest(BaseModel):
    """Schema for the topic/language input for video/notes generation."""
    topic: str
    language: str

class TopicVideoResponse(BaseModel):
    """Schema for the video suggestion and notes output (API Response)."""
    video_title: str
    video_url: str
    notes_markdown: str

# Schema for the database model (for CRUD and retrieval)
class VideoNoteEntryBase(BaseModel):
    """Base schema for saving the video note entry to the DB."""
    topic: str
    language: str
    video_title: str
    video_url: str
    notes_markdown: str

# 👇 FIX: Add the missing 'VideoNoteEntryCreate' class
class VideoNoteEntryCreate(VideoNoteEntryBase):
    """Schema for creating a video note entry in the DB."""
    pass

class VideoNoteEntry(VideoNoteEntryBase):
    """Schema for returning a video note entry."""
    id: int
    user_id: int
    timestamp: str
    
    class Config:
        from_attributes = True
class SubjectConstraint(BaseModel):
    """Schema for a single subject input."""
    subject: str = Field(..., description="The name of the subject, e.g., 'Math'.")
    chapters: int = Field(..., description="The number of chapters to complete for this subject.", gt=0)

class TimetableRequest(BaseModel):
    """Request schema for generating a timetable."""
    subjects: List[SubjectConstraint] = Field(..., description="List of subjects and their chapter counts.")
    total_days: int = Field(..., description="The total number of days available for study.", gt=0)

class TimetableResponse(BaseModel):
    """Response schema for the generated timetable."""
    # This field holds the Markdown string generated by Gemini
    timetable_markdown: str = Field(..., description="The generated timetable in Markdown format.")